---
version: '3'
services:
  sso-server:
    image: ducminh210503/sso-server:latest
    container_name: sso-server
    ports:
      - "8081:8080"
    networks:
      - dormy-network

  review-server:
    image: ducminh210503/review-server:latest
    container_name: review-server
    ports:
      - "8082:8080"
    networks:
      - dormy-network

  notification-server:
    image: ducminh210503/notification-server:latest
    container_name: notification-server
    ports:
      - "8083:8080"
    networks:
      - dormy-network

  media-server:
    image: ducminh210503/media-server:latest
    container_name: media-server
    ports:
      - "8084:8080"
    networks:
      - dormy-network

  interaction-server:
    image: ducminh210503/interaction-server:latest
    container_name: interaction-server
    ports:
      - "8085:8080"
    networks:
      - dormy-network

  friends-server:
    image: ducminh210503/friends-server:latest
    container_name: friends-server
    ports:
      - "8086:8080"
    networks:
      - dormy-network

  feed-server:
    image: ducminh210503/feed-server:latest
    container_name: feed-server
    ports:
      - "8087:8080"
    networks:
      - dormy-network

  discovery-server:
    image: ducminh210503/discovery-server:latest
    container_name: discovery-server
    ports:
      - "8088:8080"
    networks:
      - dormy-network

  chat-server:
    image: ducminh210503/chat-server:latest
    container_name: chat-server
    ports:
      - "8089:8080"
    networks:
      - dormy-network

  api-gateway:
    image: ducminh210503/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8090:8080"
    networks:
      - dormy-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-dormy
    ports:
      - "9411:9411"
    networks:
      - dormy-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
    user: "0:0"
    networks:
      - dormy-network

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - 9092:9092
    expose:
      - 9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENER: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    restart: always
    user: "0:0"
    networks:
      - dormy-network

  redis:
    container_name: redis-dormy
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./redis-data:/data
    networks:
      - dormy-network

  dormy-data:
    container_name: dormy-data
    image: postgres:12-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=${DB_DATA}
    command: -p ${DB_PORT}
    volumes:
      - ./${DB_LOCAL_DIR}:${DB_DATA}
      - ./init.local.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    networks:
      - dormy-network

  dormy-pgadmin:
    container_name: dormy-pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin4_data:/var/lib/pgadmin4/data
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5050:80"
    depends_on:
      - dormy-data
    restart: on-failure
    networks:
      - dormy-network

volumes:
  pgadmin4_data: { }

networks:
  dormy-network:
    driver: bridge