eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: sso
          uri: lb://sso-service
          predicates:
            - Path=/api/v1/auth/**

        - id: users
          uri: lb://sso-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter


        - id: comments
          uri: lb://interactions-service
          predicates:
            - Path=/api/v1/comments/**
          filters:
            - AuthenticationFilter


        - id: shareds
          uri: lb://interactions-service
          predicates:
            - Path=/api/v1/shareds/**
          filters:
            - AuthenticationFilter


        - id: reactions
          uri: lb://interactions-service
          predicates:
            - Path=/api/v1/reactions/**
          filters:
            - AuthenticationFilter


        - id: interactions
          uri: lb://interactions-service
          predicates:
            - Path=/api/v1/interactions/**
          filters:
            - AuthenticationFilter


        - id: users-auth
          uri: http://localhost:8101
          predicates:
            - Path=/api/v1/auth/**


#        - id: users-data
#          uri: http://localhost:8083
#          predicates:
#            - Path=/api/v1/users/**
#          filters:
#            - AuthenticationFilter


        - id: medias
          uri: lb://media-service
          predicates:
            - Path=/api/v1/medias/**
          filters:
            - AuthenticationFilter


        - id: friend-services
          uri: lb://friend-service
          predicates:
            - Path=/api/v1/friend/**
          filters:
            - AuthenticationFilter


        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/v1/post/**
          filters:
            - AuthenticationFilter


        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - AuthenticationFilter

        - id: feed-service
          uri: lb://feed-service
          predicates:
            - Path=/api/v1/feeds/**
          filters:
            - AuthenticationFilter


    #/api/friend-requests
    discovery:
      enabled: true
    config:
      enabled: false


management:
  tracing:
    sampling:
      probability: 1.0




