eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

spring:
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: feed-service
  cloud:
    config:
      enabled: false
    openfeign:
      circuitbreaker:
        enabled: true
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5430/friend_service
#    username: postgres
#    password: postgres
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  cloud:
#    config:
#      enabled: false

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 4
        waitDurationInOpenState: 10000

server:
  port: 8085
