eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

server:
  port: 8016
spring:
  application:
    name: media-service
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: saveImageTopic
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/media_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: full

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      enabled: true
      file-size-threshold: 2KB

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

file:
  upload-dir: /home/maro/IdeaProjects/social-network-microservice/images

#management:
#  tracing:
#    sampling:
#      probability: 1.0
